/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Oli
 */
public class PatientDashboard extends javax.swing.JFrame {

    private String id;
    /**
     * Creates new form PatientDashboard
     */
    public PatientDashboard() {
        initComponents();
        
    }
    
    public void showInfo(String nextApp, String[] appHistory, String[] prescription, String parentID)
    {
        id = parentID;
        txa_nextApp.setText(nextApp);
        
        DefaultListModel listHistory;
        listHistory = new DefaultListModel();
        for (int i = 0; i < appHistory.length; i++) {
            listHistory.addElement(appHistory[i]);
        }
        lst_history.setModel(listHistory);
        
        DefaultListModel listPrescription;
        listPrescription = new DefaultListModel();
        for (int i = 0; i < prescription.length; i++) {
            if (prescription[i].length() < 60) {
                listPrescription.addElement(prescription[i]);
            }
            else
            {
                for (int j = 0; 60 < (prescription[i].length() - (j*60)); j++) {
                    listPrescription.addElement(prescription[i].substring(60 * j, 60* j + 60));
                    if ((prescription[i].length() - ((j + 1) * 60) < 60)) 
                    {
                        listPrescription.addElement(prescription[i].substring(60 * (j + 1)));
                    }
                }

            }
                
        }
        lst_prescription.setModel(listPrescription);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txa_nextApp = new javax.swing.JTextArea();
        btn_app = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_prescription = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_history = new javax.swing.JList<>();
        btn_accDel = new javax.swing.JButton();
        sdr_rate = new javax.swing.JSlider();
        lbl_welcome = new javax.swing.JLabel();
        lbl_rate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setName("txt_nextApp\n"); // NOI18N

        txa_nextApp.setColumns(20);
        txa_nextApp.setRows(5);
        txa_nextApp.setText("Your Next appointment will appear here...");
        txa_nextApp.setMaximumSize(new java.awt.Dimension(333, 333));
        txa_nextApp.setName("txt_nextApp"); // NOI18N
        jScrollPane1.setViewportView(txa_nextApp);

        btn_app.setLabel("Request Appointment");
        btn_app.setName("btn_requestApp"); // NOI18N
        btn_app.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_appActionPerformed(evt);
            }
        });

        jScrollPane2.setName("lst_Prescriptions"); // NOI18N

        lst_prescription.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Current Prescriptions" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lst_prescription);

        lst_history.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Appointment History" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lst_history.setName("lst_appHistory"); // NOI18N
        jScrollPane3.setViewportView(lst_history);

        btn_accDel.setText("Delete Account");
        btn_accDel.setName("btn_delete"); // NOI18N
        btn_accDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accDelActionPerformed(evt);
            }
        });

        sdr_rate.setMaximum(10);
        sdr_rate.setPaintLabels(true);
        sdr_rate.setPaintTicks(true);
        sdr_rate.setSnapToTicks(true);
        sdr_rate.setValue(5);
        sdr_rate.setName("sld_rate"); // NOI18N

        lbl_welcome.setText("Welcome Back...");
        lbl_welcome.setName("lbl_title"); // NOI18N

        lbl_rate.setText("Rate this doctor");
        lbl_rate.setName("lbl_rate"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btn_app))
                            .addComponent(jScrollPane3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_accDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sdr_rate, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_rate)
                                .addGap(12, 12, 12))))
                    .addComponent(lbl_welcome))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lbl_welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_app)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_rate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sdr_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btn_accDel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_appActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_appActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_appActionPerformed

    private void btn_accDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accDelActionPerformed
        try {
            boolean pending = false;
            File textFile = new File("D://SOFT252//SOFT252//Coursework//Data.txt");
            Scanner scan;
            
            scan = new Scanner(textFile);
            int lineCount = 0;
            
            while(scan.hasNextLine())
            {
                if(scan.nextLine().equals("DeleteRequest"))
                {
                    if (scan.nextLine().equals(id))
                    {
                        pending = true;
                    }
                    lineCount++;
                }
                lineCount++;
            }
            
            scan.close();
            if(pending == false){
                String[] data = new String[lineCount + 1];
                scan = new Scanner(textFile);
                int i = 0;

                while(scan.hasNextLine())
                {
                    data[i] = scan.nextLine();
                    if (data[i].equals(id))
                    {
                        data[i + 1] = data[i];
                        data[i] = "DeleteRequest";
                        i++;
                    }
                    i++;
                }

                scan.close();

                try {
                    FileWriter write = new FileWriter(textFile, false);
                    write.flush();
                    for (int j = 0; j < data.length; j++) {
                        write.write(data[j]);
                        System.out.println(data[j]);
                        write.write(System.getProperty( "line.separator" ));
                    }
                    write.close();


                } catch (IOException ex) {
                    Logger.getLogger(SecretaryDashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PatientDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_btn_accDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accDel;
    private javax.swing.JButton btn_app;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_rate;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JList<String> lst_history;
    private javax.swing.JList<String> lst_prescription;
    private javax.swing.JSlider sdr_rate;
    private javax.swing.JTextArea txa_nextApp;
    // End of variables declaration//GEN-END:variables
}
