/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import javax.swing.DefaultListModel;

/**
 *
 * @author Oli
 */
public class PatientDashboard extends javax.swing.JFrame {

    /**
     * Creates new form PatientDashboard
     */
    public PatientDashboard() {
        initComponents();
        
    }
    
    public void showInfo(String nextApp, String[] appHistory, String[] prescription)
    {
        jTextAreaNextApp.setText(nextApp);
        
        DefaultListModel listHistory;
        listHistory = new DefaultListModel();
        for (int i = 0; i < appHistory.length; i++) {
            listHistory.addElement(appHistory[i]);
        }
        jListHistory.setModel(listHistory);
        
        DefaultListModel listPrescription;
        listPrescription = new DefaultListModel();
        for (int i = 0; i < prescription.length; i++) {
            if (prescription[i].length() < 60) {
                listPrescription.addElement(prescription[i]);
            }
            else
            {
                for (int j = 0; 60 < (prescription[i].length() - (j*60)); j++) {
                    listPrescription.addElement(prescription[i].substring(60 * j, 60* j + 60));
                    if ((prescription[i].length() - ((j + 1) * 60) < 60)) 
                    {
                        listPrescription.addElement(prescription[i].substring(60 * (j + 1)));
                    }
                }

            }
                
        }
        jListPrescriptions.setModel(listPrescription);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNextApp = new javax.swing.JTextArea();
        jButtonApp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPrescriptions = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListHistory = new javax.swing.JList<>();
        jButtonDelete = new javax.swing.JButton();
        jSliderRate = new javax.swing.JSlider();
        jLabelWelcome = new javax.swing.JLabel();
        jLabelRate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setName("txt_nextApp\n"); // NOI18N

        jTextAreaNextApp.setColumns(20);
        jTextAreaNextApp.setRows(5);
        jTextAreaNextApp.setText("Your Next appointment will appear here...");
        jTextAreaNextApp.setMaximumSize(new java.awt.Dimension(333, 333));
        jTextAreaNextApp.setName("txt_nextApp"); // NOI18N
        jScrollPane1.setViewportView(jTextAreaNextApp);

        jButtonApp.setLabel("Request Appointment");
        jButtonApp.setName("btn_requestApp"); // NOI18N
        jButtonApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppActionPerformed(evt);
            }
        });

        jScrollPane2.setName("lst_Prescriptions"); // NOI18N

        jListPrescriptions.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Current Prescriptions" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListPrescriptions);

        jListHistory.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Appointment History" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListHistory.setName("lst_appHistory"); // NOI18N
        jScrollPane3.setViewportView(jListHistory);

        jButtonDelete.setText("Delete Account");
        jButtonDelete.setName("btn_delete"); // NOI18N

        jSliderRate.setMaximum(10);
        jSliderRate.setPaintLabels(true);
        jSliderRate.setPaintTicks(true);
        jSliderRate.setSnapToTicks(true);
        jSliderRate.setValue(5);
        jSliderRate.setName("sld_rate"); // NOI18N

        jLabelWelcome.setText("Welcome Back...");
        jLabelWelcome.setName("lbl_title"); // NOI18N

        jLabelRate.setText("Rate this doctor");
        jLabelRate.setName("lbl_rate"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButtonApp))
                            .addComponent(jScrollPane3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSliderRate, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelRate)
                                .addGap(12, 12, 12))))
                    .addComponent(jLabelWelcome))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabelWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonApp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelRate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSliderRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonDelete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApp;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JLabel jLabelRate;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JList<String> jListHistory;
    private javax.swing.JList<String> jListPrescriptions;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSliderRate;
    private javax.swing.JTextArea jTextAreaNextApp;
    // End of variables declaration//GEN-END:variables
}
